"USABILITY {{{
set encoding=UTF-8
set path=src/**
set nocompatible
set backspace=2
set mouse=n
set wildmenu
set wildmode=longest:full,full
set exrc
set clipboard=unnamedplus
set noswapfile
set nowrap
set autoread
set complete=
set incsearch
set scrolloff=3
set switchbuf="usetab,uselast"
set ttyfast
set ttimeout
set ttimeoutlen=1
set nohidden
set splitbelow
set splitright
set hlsearch
let mapleader=' '
let g:work = 0
set grepprg=git-grep\ -I\ -n\ $*

vnoremap p "0p
vnoremap P "0P
autocmd BufWritePre *\(.html\|.css\|.java\|.h\|.c\) :%s/\s\+$//e
"}}}

"STATUSLINE {{{
function! StatusLineMod(winid)
  let buf = winbufnr(a:winid)
  let modified =  getbufvar(buf, '&modified')
  let readonly =  getbufvar(buf, '&readonly')
  if a:winid != win_getid()
    return ""
  endif
  if l:modified
    if a:winid == win_getid()
      return "%#StatusLineModified#[Modified]%##"
    else
      return "%#StatusLineModifiedNC#[Modified]%##"
    endif
  endif
  if l:readonly
    if a:winid == win_getid()
      return "%#StatusLineReadOnly#[ReadOnly]%##"
    else
      return "%#StatusLineReadOnlyNC#[ReadOnly]%##"
    endif
  endif
  return ""
endfunction
function! StatusLineBranch(winid)
  let buf = winbufnr(a:winid)
  let file = bufname(l:buf)
  if a:winid != win_getid()
    return ""
  endif
  :silent let branch = system("git -C " . fnamemodify(l:file, ":p:h") . " branch --show-current 2> /dev/null | tr -d '\n'")
  if branch == ""
    return ""
  endif
  let highlight = ""
  if branch == "master" || branch == "main"
    if a:winid == win_getid()
      let highlight = "%#StatusLineMaster#"
    else
      let highlight = "%#StatusLineMasterNC#"
    endif
  endif
  return highlight . "[" . branch . "]%##"
endfunction
function! StatusLineFileType(winid)
  if &filetype == ""
    return ""
  endif
  return "[" . &filetype . "]"
endfunction
function! StatusLineFile(winid)
  let buf = winbufnr(a:winid)
  let file = bufname(l:buf)
  if a:winid != win_getid()
    return ""
  endif
  if file == ""
    return ""
  endif
  return "[" . file . "]"
endfunction
function! StatusLine()
  let file = StatusLineFile(g:statusline_winid)
  let mod = StatusLineMod(g:statusline_winid)
  let branch = StatusLineBranch(g:statusline_winid)
  return file . "%=" . mod . branch
endfunction
set statusline=%!StatusLine()
"}}}

"VISUAL ONLY {{{
let &t_SI .= "\e[5 q"
let &t_SR .= "\e[3 q"
let &t_EI .= "\e[1 q"
set t_md=
set guicursor=i:blinkwait0-blinkon100-blinkoff150
if v:version >= 901
  set fillchars=eob:\ ,vert:│,stl:_,stlnc:─,fold:\ ,foldsep:│,foldopen:┬
else
  set fillchars=vert:│,stl:_,stlnc:─,fold:\ 
endif
set noruler
set nonumber
set laststatus=2
set signcolumn=auto
set conceallevel=2

if g:work == 1
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
endif
colo custom
"}}}

"GVIM {{{
set guifont=Custom
set guioptions=r
"}}}

"INDENT {{{
set autoindent
set shiftwidth=2
set tabstop=2
set softtabstop=2
set expandtab
autocmd FileType c set noautoindent
autocmd FileType c set cindent
"}}}

"FOLDS {{{
set foldlevel=0
set foldnestmax=10
set foldcolumn=0
function! Common_FoldText()
  let foldtext = substitute(
        \    substitute(substitute(substitute(
        \    substitute(getline(v:foldstart),
        \    '^"\+\s*',                '',                                  ''),
        \    '\s*/\*\s*',   '',                     ''),
        \    '\s*\*/\s*',   '',                     ''),
        \    '^\s*//\s*',            '',                                  ''),
        \    '^\s\+',                '\=repeat("─",strlen(submatch(0)))', '')
  if foldtext == ""
    return getline(v:foldstart)
  endif
  return foldtext
endfunction
function! C_FoldText()
  let foldtext = substitute(Common_FoldText(),
        \ '\s*\\$',             '',                                  '')
  if foldtext == ""
    return getline(v:foldstart)
  endif
  return foldtext
endfunction
function! FoldText()
  let foldtext = substitute(Common_FoldText(),
        \ '^#\s*',              '',                                  '')
  if foldtext == ""
    return getline(v:foldstart)
  endif
  return foldtext
endfunction

set foldexpr=FoldMethod(v:lnum)
let javaScript_fold=1
autocmd FileType c          set foldmethod=syntax
autocmd FileType cpp        set foldmethod=syntax
autocmd FileType javascript set foldmethod=syntax
autocmd FileType java       set foldmethod=syntax
autocmd FileType java       set foldlevel=1
autocmd FileType css        set foldmethod=marker
autocmd FileType html       set foldmethod=indent
autocmd FileType html       set foldlevel=5
autocmd FileType python     set foldmethod=indent
autocmd FileType vim        set foldmethod=marker
autocmd FileType conf       set foldmethod=marker
autocmd FileType sh         set foldmethod=indent
autocmd FileType i3config   set foldmethod=marker

autocmd FileType * set foldtext=FoldText()
autocmd FileType c,cpp,h,hpp set foldtext=C_FoldText()
"}}}

"PLUGINS {{{
call plug#begin()
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-fugitive'
Plug 'powerman/vim-plugin-AnsiEsc'
Plug 'matze/vim-move'
Plug 'tpope/vim-commentary'
Plug 'skywind3000/asyncrun.vim'
Plug 'vim-scripts/cmdalias.vim'
Plug 'rhysd/vim-clang-format'
Plug 'Konfekt/FastFold'
Plug 'aymericbeaumet/vim-symlink'
Plug 'Jorengarenar/vim-syntaxMarkerFold'
Plug 'tpope/vim-eunuch'
if v:version >= 901
  Plug 'bfrg/vim-qf-diagnostics'
endif
call plug#end()
if g:work == 1
  let g:clang_format#auto_format = 0
  let g:clang_format#auto_formatexpr = 0
  let g:clang_format#detect_style_file = 1
  let g:clang_format#enable_fallback_style = 0
else
  let g:clang_format#auto_format = 1
  let g:clang_format#auto_formatexpr = 1
  let g:clang_format#detect_style_file = 1
  let g:clang_format#enable_fallback_style = 0
endif
" let g:tex_flavor='latex'
" let g:vimtex_quickfix_open_on_warning = 0
" let g:vimtex_view_method = 'mupdf'
" let g:vimtex_compiler = 'latexmk'
" augroup VimTeX
"   autocmd!
"   autocmd BufReadPre *.tex
"         \ let b:vimtex_main = 'main.tex'
" augroup end

if v:version >= 901
  let g:qfdiagnostics = {
        \  'texthl': 1,
        \  'sign_error': { 'text': '*', 'priority': 14, 'texthl': 'SignError'},
        \  'sign_warning': { 'text': '*', 'priority': 13, 'texthl': 'SignWarning'},
        \  'sign_info': { 'text': '*', 'priority': 12, 'texthl': 'SignInfo'},
        \  'sign_note': { 'text': '*', 'priority': 11, 'texthl': 'SignNote'},
        \  'sign_other': { 'text': '*', 'priority': 10, 'texthl': 'SignOther'},
        \}
  autocmd QuickfixCmdPost  make  DiagnosticsPlace
  autocmd User AsyncRunStop DiagnosticsPlace
endif
let g:move_key_modifier = 'C'
let g:move_key_modifier_visualmode = 'C'
autocmd BufWritePost * :GitGutter
"}}}

"SYNTAX {{{
function! s:syntax_query() abort
  for id in synstack(line("."), col("."))
    echo synIDattr(id, "name")
  endfor
endfunction
command! SyntaxQuery call s:syntax_query()
au! Syntax markdown source syntax/markdown.vim
filetype on
filetype plugin on
filetype indent on
syntax on
autocmd Syntax * syn sync fromstart
autocmd Syntax * syn match Important /.TODO.*/hs=s+1 containedin=.*Comment.*
autocmd Syntax * syn region Important start="!:" end=":!\|\n" containedin=.*Comment.*
autocmd Syntax * set formatoptions=rqn2jc
autocmd Syntax tex,markdown set formatoptions+=t

au BufRead,BufNewFile *.cu set filetype=cpp
"}}}

"PROGRAMMING {{{
set errorformat^=%f:%l-%e:%c-%k\ [%t%*[a-z]]\ %m,%f:%l-%e:%c-%k\ [%t%n]\ %m,%f:%l:%c\ style:\ %m,%f:%l:%c:\ %t%*[^\ ]\ %m,%.%#[%f\|%l\|%t]\ %m,
let c_gnu=1
let c_comment_strings=0
let c_space_errors=1
let c_syntax_for_h=1
set cinoptions=:0,b1,(0,c0,L0,l1
set cinkeys=0=break,o,O,e,i,=if,0=switch,=for,=while,0},0{,0),0],;,0#,*<Return>
if g:work == 1
  set textwidth=100
else
  set textwidth=80
endif
packadd! termdebug
let g:termdebug_wide=1
let g:termdebug_popup = 0
let g:termdebug_use_prompt = 1
if g:work == 1
  au VimEnter * call CmdAlias("f", "Cfind -name")
else
  au VimEnter * call CmdAlias("f", "find")
endif
au VimEnter * call CmdAlias("gr", "grep --recurse-submodules")
au VimEnter * call CmdAlias("ga", "Git add")
au VimEnter * call CmdAlias("gc", "Git commit")
au VimEnter * call CmdAlias("gca", "Git commit --amend")
au VimEnter * call CmdAlias("gpl", "Git pull")
au VimEnter * call CmdAlias("gph", "Git push")
au VimEnter * call CmdAlias("gch", "Git checkout")
au VimEnter * call CmdAlias("gst", "Git status")
au VimEnter * call CmdAlias("gsh", "Git show")
au VimEnter * call CmdAlias("gshn", "Git show --name-only")
au VimEnter * call CmdAlias("gd", "Gvdiffsplit!")
au VimEnter * call CmdAlias("g", "grep")
au VimEnter * call CmdAlias("m", "make")
au VimEnter * call CmdAlias("ma", "make all")
au VimEnter * call CmdAlias("co", "botright copen")
au VimEnter * call CmdAlias("copen", "botright copen")
au VimEnter * call CmdAlias("vf", "vert sf")
au VimEnter * call CmdAlias("t", "tab")
au VimEnter * call CmdAlias("te", "tabedit")
runtime! macros/matchit.vim
runtime ftplugin/man.vim
autocmd Syntax c set commentstring=//%s
autocmd Syntax cpp set commentstring=//%s
autocmd CursorHold * checktime

function! SetCC(val)
  let &colorcolumn=join(range(a:val,999),",")
endfunction
function! ClearCC()
  set colorcolumn=0
endfunction

if g:work == 1
  call SetCC(100)
else
  autocmd Syntax c call SetCC(81)
  autocmd Syntax cpp call SetCC(81)
  autocmd Syntax vim call SetCC(81)
  call ClearCC()
endif
"}}}

" WORK {{{
function! Test()
  let l:output = system('change ' . shellescape(expand("%:p")) . ' test')
  execute ':edit ' . l:output
endfunction

function! Body()
  let l:output = system('change ' . shellescape(expand("%:p")) . ' body')
  execute ':edit ' . l:output
endfunction

function! ApiPrivate()
  let l:output = system('change ' . shellescape(expand("%:p")) . ' api-private')
  execute ':edit ' . l:output
endfunction

function TraceInfo()
  :r !next-trace
  :normal ITRACE_INFO_UID(MH.
  :normal $a, "", NO_ARG);
  :normal 10h
endfunction

function TraceBus()
  :r !next-trace
  :normal ITRACE_BUS_WH_UID(MH.
  :normal $a, CM_NULL, , , "", NO_ARG);
  :normal 15h
endfunction

if g:work == 1
  command T call Test()
  command B call Body()
  command A call ApiPrivate()
  command TI call TraceInfo()
  command TB call TraceBus()
endif
" }}}
