"USABILITY {{{
set encoding=UTF-8
set path=src/**
set nocompatible
set backspace=2
set wildmenu
set wildmode=longest:full,full
set exrc
set clipboard=unnamedplus
set noswapfile
set nowrap
set autoread
set complete=
set incsearch
set so=3
set switchbuf="useopen,vsplit,hsplit"
set ttyfast
set ttimeout
set ttimeoutlen=1
set nohidden
set splitbelow
set splitright
let mapleader=' '

vnoremap p "0p
vnoremap P "0P
autocmd BufWritePre *\(.html\|.css\|.java\|.h\|.c\) :%s/\s\+$//e
"}}}

"STATUSLINE {{{
function! StatusLineMod(winid)
  let buf = winbufnr(a:winid)
  let modified =  getbufvar(buf, '&modified')
  let readonly =  getbufvar(buf, '&readonly')
  if a:winid != win_getid()
    return ""
  endif
  if l:modified
    if a:winid == win_getid()
      return "%#StatusLineModified#[Modified]%##"
    else
      return "%#StatusLineModifiedNC#[Modified]%##"
    endif
  endif
  if l:readonly
    if a:winid == win_getid()
      return "%#StatusLineReadOnly#[ReadOnly]%##"
    else
      return "%#StatusLineReadOnlyNC#[ReadOnly]%##"
    endif
  endif
  return ""
endfunction
function! StatusLineBranch(winid)
  let buf = winbufnr(a:winid)
  let file = bufname(l:buf)
  if a:winid != win_getid()
    return ""
  endif
  :silent let branch = system("git -C " . fnamemodify(l:file, ":p:h") . " branch --show-current 2> /dev/null | tr -d '\n'")
  if branch == ""
    return ""
  endif
  let highlight = ""
  if branch == "master" || branch == "main"
    if a:winid == win_getid()
      let highlight = "%#StatusLineMaster#"
    else
      let highlight = "%#StatusLineMasterNC#"
    endif
  endif
  return highlight . "[" . branch . "]%##"
endfunction
function! StatusLineFileType(winid)
  if &filetype == ""
    return ""
  endif
  return "[" . &filetype . "]"
endfunction
function! StatusLineFile(winid)
  let buf = winbufnr(a:winid)
  let file = bufname(l:buf)
  if a:winid != win_getid()
    return ""
  endif
  if file == ""
    return ""
  endif
  return "[" . file . "]"
endfunction
function! StatusLine()
  let file = StatusLineFile(g:statusline_winid)
  let mod = StatusLineMod(g:statusline_winid)
  let branch = StatusLineBranch(g:statusline_winid)
  return file . "%=" . mod . branch
endfunction
set statusline=%!StatusLine()
"}}}

"VISUAL ONLY {{{
let &t_SI .= "\e[5 q"
let &t_SR .= "\e[3 q"
let &t_EI .= "\e[1 q"
set guicursor=i:blinkwait0-blinkon100-blinkoff150
set fillchars=eob:\ ,vert:│,stl:─,stlnc:─,fold:\ ,foldsep:│,foldopen:┬
set noruler
set nonumber
set laststatus=2
set signcolumn=yes
set conceallevel=2

augroup CursorLine
    au!
    au WinNew * setlocal nocursorline
    au VimEnter * setlocal cursorline
    au WinEnter * setlocal cursorline
    au BufWinEnter * setlocal cursorline
    au WinLeave * setlocal nocursorline
augroup END
colo custom
"}}}

"GVIM {{{
set guifont=Code\ New\ Roman\\,\ 14
set guioptions=r
"}}}

"INDENT {{{
set autoindent
set shiftwidth=2
set tabstop=2
set softtabstop=2
set expandtab
autocmd FileType c set noautoindent
autocmd FileType c set cindent
"}}}

"FOLDS {{{
set foldlevel=0
set foldnestmax=0
set foldcolumn=0
function! Common_FoldText()
  let foldtext = substitute(
        \    substitute(substitute(substitute(
        \    substitute(substitute(getline(v:foldstart),
        \    '{\+\s*\(\*/\)\?\s*$', '',                                  ''),
        \    '^"\s*',                '',                                  ''),
        \    '\s*/\*\s*',   '',                     ''),
        \    '\s*\*/\s*',   '',                     ''),
        \    '^\s*//\s*',            '',                                  ''),
        \    '^\s\+',                '\=repeat("─",strlen(submatch(0)))', '')
  if foldtext == ""
    return getline(v:foldstart)
  endif
  return foldtext
endfunction
function! C_FoldText()
  let foldtext = substitute(Common_FoldText(),
        \ '\s*\\$',             '',                                  '')
  if foldtext == ""
    return getline(v:foldstart)
  endif
  return foldtext
endfunction
function! FoldText()
  let foldtext = substitute(Common_FoldText(),
        \ '^#\s*',              '',                                  '')
  if foldtext == ""
    return getline(v:foldstart)
  endif
  return foldtext
endfunction

set foldexpr=FoldMethod(v:lnum)
let javaScript_fold=1
autocmd FileType c          set foldmethod=syntax
autocmd FileType c          set foldnestmax=5
autocmd FileType cpp        set foldmethod=syntax
autocmd FileType cpp        set foldnestmax=2
autocmd FileType javascript set foldmethod=syntax
autocmd FileType javascript set foldnestmax=1
autocmd FileType alang      set foldmethod=syntax
autocmd FileType alang      set foldnestmax=5
autocmd FileType java       set foldmethod=syntax
autocmd FileType java       set foldlevel=1
autocmd FileType java       set foldnestmax=2
autocmd FileType css        set foldmethod=marker
autocmd FileType css        set foldnestmax=1
autocmd FileType html       set foldmethod=indent
autocmd FileType html       set foldlevel=5
autocmd FileType htmldjango set foldmethod=indent
autocmd FileType htmldjango set foldlevel=5
autocmd FileType python     set foldmethod=indent
autocmd FileType python     set foldnestmax=1
autocmd FileType vim        set foldmethod=marker
autocmd FileType vim        set foldnestmax=1
autocmd FileType i3config   set foldmethod=marker
autocmd FileType i3config   set foldnestmax=2
autocmd FileType conf       set foldmethod=marker
autocmd FileType conf       set foldnestmax=2
autocmd FileType sh         set foldmethod=indent
autocmd FileType sh         set foldnestmax=1

autocmd FileType * set foldtext=FoldText()
autocmd FileType c,cpp,h,hpp set foldtext=C_FoldText()
"}}}

"PLUGINS {{{
call plug#begin()
Plug 'https://github.com/ludovicchabant/vim-gutentags'
Plug 'https://github.com/vim-scripts/taglist.vim'
Plug 'https://github.com/chazy/cscope_maps'
Plug 'https://github.com/airblade/vim-gitgutter'
Plug 'https://github.com/tpope/vim-fugitive'
Plug 'https://github.com/mikelue/vim-maven-plugin'
Plug 'https://github.com/powerman/vim-plugin-AnsiEsc'
Plug 'https://github.com/gregsexton/matchtag'
Plug 'https://github.com/matze/vim-move'
Plug 'https://github.com/bfrg/vim-qf-diagnostics'
Plug 'https://github.com/tpope/vim-commentary'
Plug 'https://github.com/machakann/vim-sandwich'
Plug 'https://github.com/lervag/vimtex'
Plug 'https://github.com/skywind3000/asyncrun.vim'
Plug 'https://github.com/vim-scripts/cmdalias.vim'
Plug 'https://github.com/rhysd/vim-clang-format'
Plug 'https://github.com/Konfekt/FastFold'
Plug 'aymericbeaumet/vim-symlink'
Plug 'Jorengarenar/vim-syntaxMarkerFold'
Plug 'moll/vim-bbye'
call plug#end()
let g:clang_format#auto_format = 1
let g:clang_format#auto_formatexpr = 1
let g:clang_format#detect_style_file = 1
let g:clang_format#enable_fallback_style = 0
let g:tex_flavor='latex'
let g:vimtex_quickfix_open_on_warning = 0
let g:vimtex_view_method = 'mupdf'
let g:vimtex_compiler = 'latexmk'
augroup VimTeX
  autocmd!
  autocmd BufReadPre *.tex
        \ let b:vimtex_main = 'main.tex'
augroup end
let g:gutentags_ctags_extra_args = [
      \ '--fields=+ailmnS',
      \]
let g:gutentags_modules = ['gtags_cscope']

"TODO: Change
let g:gutentags_generate_on_new = 0
let g:gutentags_generate_on_missing = 0
let g:gutentags_generate_on_write = 0

let g:gutentags_generate_on_empty_buffer = 0
let g:gutentags_project_root = ['Makefile','README.md','pom.xml','LICENSE']
let g:gutentags_cache_dir = '.gtags'
let g:gutentags_add_default_project_roots = 0
let g:qfdiagnostics = {
      \  'texthl': 1,
      \  'sign_error': { 'text': '*', 'priority': 14, 'texthl': 'SignError'},
      \  'sign_warning': { 'text': '*', 'priority': 13, 'texthl': 'SignWarning'},
      \  'sign_info': { 'text': '*', 'priority': 12, 'texthl': 'SignInfo'},
      \  'sign_note': { 'text': '*', 'priority': 11, 'texthl': 'SignNote'},
      \  'sign_other': { 'text': '*', 'priority': 10, 'texthl': 'SignOther'},
      \}
let g:move_key_modifier = 'C'
let g:move_key_modifier_visualmode = 'C'
autocmd QuickfixCmdPost  make  DiagnosticsPlace
autocmd User AsyncRunStop DiagnosticsPlace
autocmd BufWritePost * :GitGutter
"}}}

"SYNTAX {{{
function! s:syntax_query() abort
  for id in synstack(line("."), col("."))
    echo synIDattr(id, "name")
  endfor
endfunction
command! SyntaxQuery call s:syntax_query()
au! Syntax markdown source syntax/markdown.vim
au! Syntax html source syntax/html.vim
au! Syntax alang source syntax/alang.vim
filetype on
filetype plugin on
filetype indent on
syntax on
autocmd Syntax * syn sync fromstart
autocmd Syntax * syn match Important /.TODO.*/hs=s+1 containedin=.*Comment.*
autocmd Syntax * syn region Important start="!:" end=":!\|\n" containedin=.*Comment.*
autocmd Syntax * set formatoptions=rqn2jc
autocmd Syntax tex,markdown set formatoptions+=t]
autocmd Syntax tex,markdown set textwidth=80

au BufRead,BufNewFile *.c,*.h set syntax=custom-c
au BufRead,BufNewFile *.alang set filetype=custom-alang
au BufRead,BufNewFile Makefile set syntax=custom-make
au BufRead,BufNewFile *.py set syntax=custom-python
au BufRead,BufNewFile *.ejs set filetype=html
au BufRead,BufNewFile *.cu set filetype=cpp
"}}}

"PROGRAMMING {{{
set tags=./tags;/
set csprg=gtags-cscope
set errorformat^=%f:%l-%e:%c-%k\ [%t%*[a-z]]\ %m,%f:%l-%e:%c-%k\ [%t%n]\ %m,%f:%l:%c\ style:\ %m,%f:%l:%c:\ %t%*[^\ ]\ %m,%.%#[%f\|%l\|%t]\ %m,
let c_gnu=1
let c_comment_strings=0
let c_space_errors=1
let c_syntax_for_h=1
set cinoptions=:0,b1,(0,c0,L0,l1
set cinkeys=0=break,o,O,e,i,=if,0=switch,=for,=while,0},0{,0),0],;,0#,*<Return>
packadd! termdebug
let g:termdebug_wide=1
let g:termdebug_popup = 0
let g:termdebug_use_prompt = 1
command -nargs=1 Javadoc execute "silent !javadocs-search <args>" | :redraw!
au VimEnter * Alias f find
au VimEnter * Alias m make
au VimEnter * call CmdAlias("ma", "make all")
au VimEnter * call CmdAlias("co", "botright copen")
au VimEnter * call CmdAlias("copen", "botright copen")
au VimEnter * call CmdAlias("vf", "vert sf")
au VimEnter * Alias run !run
au VimEnter * Alias r !run
au BufWritePost *.c,*.h,*.ino AsyncRun! -strip -program=make
runtime! macros/matchit.vim
runtime ftplugin/man.vim
autocmd Syntax c set commentstring=//%s
autocmd Syntax cpp set commentstring=//%s
autocmd Syntax java set keywordprg=:Javadoc
autocmd CursorHold * checktime

command VH vert split %:r:r.h
command VC vert split %:r:r.c
command VT vert split %:r:r.test.c
command HH split %:r:r.h
command HC split %:r:r.c
command HT split %:r:r.test.c
command H edit %:r:r.h
command C edit %:r:r.c
command T edit %:r:r.test.c

function! SetCC(val)
  let &colorcolumn=join(range(a:val,999),",")
endfunction
function! ClearCC()
  set colorcolumn=0
endfunction
autocmd Syntax c call SetCC(81)
autocmd Syntax cpp call SetCC(81)
autocmd Syntax vim call SetCC(81)
call ClearCC()
"}}}
