#!/bin/env dash
if [ "$1" = "close" ] || [ -z "$1" ]; then
  p="$(pwd)"
  path="$(dirname $(realpath "$0"))"
  dir="$(hostname -s | tr '[:upper:]' '[:lower:]')"
  cd "$path"
  stow -R -t "$HOME" "shared" "$dir"
  cd "$p"
fi
