[remote]
idle=yes
keep-open=yes
profile=yt-dl
keep-open-pause=no
force-window=immediate

[yt-dl]
ytdl-raw-options=sub-lang=none
script-opts=ytdl_hook-all_formats=yes,ytdl_hook-try_ytdl_first=yes
#,ytdl_hook-force_all_formats=no
ytdl-format=best
load-stats-overlay=yes
hls-bitrate=max
framedrop=vo

[hq]
profile=gpu-hq
hwdec=auto-copy
hwdec-codecs=all
framedrop=vo
interpolation=no
 
# no difference
#dither-depth=8
#dither=error-diffusion
#error-diffusion=floyd-steinberg
#deband=yes

[scale]
scaler-resizes-only=yes
#glsl-shaders=~~/shaders/Anime4K_Upscale_CNN_UL_x2.glsl 

[cache]
cache=yes
demuxer-thread=yes
demuxer-readahead-secs=60

[lang]
embeddedfonts=yes
demuxer-mkv-subtitle-preroll
blend-subtitles=yes
sub-fix-timing=no
sub-file-paths=Subs:Eng-Subtitles
sub-auto=all
slang=eng,en,enm
alang=ja,jp,jpn,eng,en,enm,english

[screenshot]
screenshot-format=png
screenshot-directory=/home/paczur/Multimedia/Pictures/Screenshots/mpv
screenshot-png-compression=8
screenshot-template='%F - %wh.%wM.%wS.%wT'

[audio]
volume=50
demuxer-rawaudio-rate=48000
ao=jack
audio-channels=stereo

[qol]
input-ipc-server=/tmp/mpvsocket
osc=no
fullscreen=yes

[image]
image-display-duration=inf
loop=yes

[music]
video=no
msg-level=cplayer=no,file=no
term-osd-bar=yes
fullscreen=no

[default]
video-sync=display-resample
profile=qol
profile=cache
profile=lang
profile=screenshot
profile=scale
profile=audio

[extension.mp3]
profile=music
[extension.m4a]
profile=music
[extension.flac]
profile=music
[protocol.http]
profile=yt-dl
[protocol.https]
profile=yt-dl
[extension.mkv]
profile=hq
[extension.mp4]
profile=hq
[extension.jpg]
profile=image
[extension.png]
profile=image
[extension.webp]
profile=image
[extension.gif]
profile=image
