"USABILITY {{{
set path-=/usr/include
set nocompatible
set backspace=2
set wildmenu
set wildmode=longest:full,full
set exrc
set clipboard=unnamedplus
set noswapfile
set nowrap
set complete=
set incsearch
set so=3
set switchbuf="useopen,vsplit"
set hidden
let mapleader=' '
noremap p "0p
noremap P "0P

autocmd BufWritePre *\(.html\|.css\|.java\|.h\|.c\) :%s/\s\+$//e
"}}}

"VISUAL ONLY {{{
colo custom
set fillchars=eob:\ ,vert:│,stl:─,stlnc:─,fold:\ ,foldsep:│,foldopen:┬
set noruler
set laststatus=2
set statusline=─\ %f\ %=\ %l/%L:%c\ %=\ %m\ %{FugitiveStatusline()}\ %y\ ─
let &colorcolumn=join(range(81,999),",")
set nonumber
set signcolumn=auto
set conceallevel=2
au BufWinEnter quickfix let &statusline=&statusline
"}}}

"GVIM {{{
set guifont=Code\ New\ Roman\\,\ 14
set guioptions=r
"}}}

"INDENT {{{
set autoindent
set shiftwidth=2
set tabstop=2
set softtabstop=2
set expandtab
autocmd FileType c set noautoindent
autocmd FileType c set cindent
"}}}

"FOLDS {{{
set foldlevel=0
set foldnestmax=0
function! FoldText()
    let line = substitute(substitute(
\              substitute(substitute(
\              substitute(getline(v:foldstart),
\                         '{\+', '', ''),
\                         '^"\s*', '', ''),
\                         '/\*\s*\(.*\)\s*\*/', '\=submatch(1)', ''),
\                         '^\s*//\s*', '', ''), '^#\s*', '', '')
    let lines_count = v:foldend - v:foldstart + 1
    let lines_count_text = printf("%10s", lines_count . ' lines')
    let foldchar = matchstr(&fillchars, 'fold:\zs.')
    let foldtextstart = strpart(line, 0, (winwidth(0)*2)/3)
    let foldtextend = lines_count_text . repeat(foldchar, 8)
    let foldtextlength = strlen(substitute(foldtextstart . foldtextend,
\                                          '.', 'x', 'g')) + &foldcolumn
    return foldtextstart . repeat(foldchar, winwidth(0)-foldtextlength) . foldtextend
endfunction
function! FoldColumn()
  if &foldnestmax == 0
    set foldcolumn=0
  elseif &foldnestmax == 1
    set foldcolumn=2
  else
    let &foldcolumn=&foldnestmax*2+1
  endif
endfunction

set foldexpr=FoldMethod(v:lnum)
autocmd FileType c set foldmethod=syntax
autocmd FileType c set foldnestmax=1
autocmd FileType java set foldmethod=syntax
autocmd FileType java set foldlevel=1
autocmd FileType java set foldnestmax=2
autocmd FileType css set foldmethod=marker
autocmd FileType css set foldnestmax=1
autocmd FileType html set foldmethod=indent
autocmd FileType html set foldlevel=5
autocmd FileType htmldjango set foldmethod=indent
autocmd FileType htmldjango set foldlevel=5
autocmd FileType python set foldmethod=indent
autocmd FileType python set foldnestmax=1
autocmd FileType vim set foldmethod=marker
autocmd FileType vim set foldnestmax=1
autocmd FileType i3config set foldmethod=marker
autocmd FileType i3config set foldnestmax=2

autocmd FileType * call FoldColumn()
autocmd FileType * set foldtext=FoldText()

autocmd FileType htmldjango set foldcolumn=0
"}}}

"PLUGINS {{{
call plug#begin()

Plug 'https://github.com/ludovicchabant/vim-gutentags'
Plug 'https://github.com/vim-scripts/taglist.vim'
Plug 'https://github.com/chazy/cscope_maps'
Plug 'https://github.com/airblade/vim-gitgutter'
Plug 'https://github.com/tpope/vim-fugitive'
Plug 'https://github.com/mikelue/vim-maven-plugin'
Plug 'https://github.com/powerman/vim-plugin-AnsiEsc'
Plug 'https://github.com/mattn/emmet-vim'
Plug 'https://github.com/gregsexton/matchtag'
Plug 'https://github.com/matze/vim-move'
Plug 'https://github.com/vim-scripts/sudo.vim'
Plug 'https://github.com/bfrg/vim-qf-diagnostics'
Plug 'https://github.com/tpope/vim-commentary'
Plug 'https://github.com/machakann/vim-sandwich'
Plug 'https://github.com/sheerun/vim-polyglot'

call plug#end()
let g:gutentags_ctags_extra_args = [
      \ '--fields=+ailmnS'
      \]
let g:gutentags_modules = ['gtags_cscope']
let g:gutentags_generate_on_new = 1
let g:gutentags_generate_on_missing = 1
let g:gutentags_generate_on_write = 1
let g:gutentags_generate_on_empty_buffer = 0
let g:gutentags_project_root = ['Makefile','GTAGS','GPATH','GRTAGS'
      \,'README.md','.gitignore','LICENSE']
let g:gutentags_add_default_project_roots = 0
let g:qfdiagnostics = {
      \  'texthl': 0,
      \  'sign_error': { 'text': '●', 'priority': 14, 'texthl': 'ErrorMsg'},
      \  'sign_warning': { 'text': '●', 'priority': 13, 'texthl': 'WarningMsg'},
      \  'sign_info': { 'text': '●', 'priority': 12, 'texthl': 'MoreMsg'},
      \  'sign_note': { 'text': '●', 'priority': 11, 'texthl': 'MoreMsg'},
      \  'sign_other': { 'text': '●', 'priority': 10, 'texthl': 'ErrorMsg'},
      \}
let g:move_key_modifier = 'C'
let g:move_key_modifier_visualmode = 'C'
autocmd QuickfixCmdPost  make  DiagnosticsPlace
autocmd BufWritePost * :GitGutter
"}}}

"SYNTAX {{{
function! s:syntax_query() abort
  for id in synstack(line("."), col("."))
    echo synIDattr(id, "name")
  endfor
endfunction
command! SyntaxQuery call s:syntax_query()
au! Syntax markdown source syntax/markdown.vim
au! Syntax html source syntax/html.vim
filetype on
filetype plugin on
filetype indent on
syntax on
autocmd Syntax * syn region Important start="[^ ]*TODO" end="\n" containedin=.*omment.*
autocmd Syntax * syn region Important start="!:" end=":!\|\n" containedin=.*omment.*
autocmd Syntax * syn match comment "\v(^#include.*\n)+" fold
autocmd Syntax * syn match comment "\v(^import.*\n)+" fold
autocmd Syntax * syn region CommentBlock start="/\*" end="\*/" transparent keepend extend fold
autocmd Syntax * syn match comment "\v(^\s*//.*\n)+" fold
autocmd Syntax * set formatoptions=rqn2jc
"}}}

"PROGRAMMING {{{
set tags=./tags;/
set csprg=gtags-cscope
set errorformat^=%f:%l:%c\ style:\ %m,%f:%l:%c:\ %t%*[^\ ]\ %m
let c_gnu=1
let c_comment_strings=1
let c_space_errors=1
let c_syntax_for_h=1
set cinoptions=:0,b1,(0,c0
set cinkeys=0=break,o,O,e,i,=if,0=switch,=for,=while,0},0{,0),0],;,0#,*<Return>
packadd termdebug
let g:termdebug_wide=1
let g:termdebug_popup = 0
let g:termdebug_use_prompt = 1
command -nargs=1 Javadoc execute "silent !javadocs-search <args>" | :redraw!
cnoreabbrev f find
autocmd Syntax java set keywordprg=:Javadoc
autocmd Syntax java set path+=**/src/main/java/**
autocmd Syntax python,html,htmldjango,css set path+=**/templates/*,**/static/**
autocmd Syntax c set path+=modules/**
autocmd Syntax scala set path+=**/src/main/scala/**
"}}}
