#!/bin/env bash
old="${full_text}"

if [ -d /sys/class/net/eth0 ]; then
  if [ "$(cat /sys/class/net/eth0/operstate)" = "up" ]; then
    if [ "$(cat /sys/class/net/eth0/carrier)" = "1" ]; then
      status="󰌘"
    else
      status="󱘖"
    fi
  else
    status="󰌙"
  fi
fi

if [ -d /sys/class/net/wlan0 ]; then
  if [ -n "$status" ]; then
    status="$status "
  fi
  if [ "$(cat /sys/class/net/wlan0/operstate)" = "up" ]; then
    status="$status󰖩"
    ssid="$(iwgetid | sed 's/wlan0 \+ESSID:"\(.*\)"/\1/')"
    if [ -n "$ssid" ]; then
      status="$status $ssid"
    else
      scan="true"
    fi
  else
    status="$status󰖪"
    scan="true"
  fi
fi

if [ -n "$scan" ]; then
  wpa_cli scan &> /dev/null
fi

if [ -n "$button" ]; then
  nohup < <(
  for i in $(seq 0 40); do
    sleep 0.5
    pkill -SIGRTMIN+12 i3blocks
  done)
fi

echo "$status"

if [ -n "$old" ] && [ "$old" != "$status" ]; then
  nohup < <(sleep 2 && pkill -SIGRTMIN+12 i3blocks)
  exit 33
fi
