#!/bin/env bash

if [ "$button" = "1" ]; then
  volume m
elif [ "$button" = "4" ]; then
  volume +
elif [ "$button" = "5" ]; then
  volume -
fi

old="$full_text"

value="$(volume g)"
set -- $value
if [ $1 = muted ]; then
  label=""
  value="$2"
else
  label=""
fi
echo "$label $value"
