#!/bin/env dash

charge_now="$(cat /sys/class/power_supply/BAT0/energy_now)"
charge_full="$(cat /sys/class/power_supply/BAT0/energy_full)"
percent="$(($charge_now*100/$charge_full))"

if [ "$(cat /sys/class/power_supply/BAT0/status)" != "Discharging" ]; then
  status=""
elif [ $percent -le 13 ]; then
  echo " $percent%" #full_text
  echo " $percent%" #short_text
  echo "#111111" #color
  echo "#f36e6e" #background
  echo "#f36e6e" #border
  exit
elif [ $percent -le 38 ]; then
  echo " $percent%" #full_text
  exit 33
elif [ $percent -le 63 ]; then
  status=""
elif [ $percent -le 88 ]; then
  status=""
else
  status=""
fi

echo "$status $percent%"
