#!/bin/env bash
old="${full_text}"
value=$(xbacklight -get)
if [ -n "$value" ]; then
  value="${value%.*}%"
  echo "$value"
fi
if [ -n "$old" ] && [ "$old" != "$label$value" ]; then
  nohup < <(sleep 2 && pkill -SIGRTMIN+11 i3blocks)
  exit 33
fi
