#!/bin/env bash
query="$(nvidia-smi --format=csv --query-gpu=utilization.gpu)"
fp=($query)
if [ "$fp" = "Failed" ]; then
  echo "Reboot"
else
  echo "$(echo "$query" | sed '1d' | rev | cut -c3- | rev)%"
fi
