#!/bin/env bash
full=""
if [ -d /sys/class/net/wlan0 ]; then
  if [ "$(cat /sys/class/net/wlan0/operstate)" = "up" ]; then
    wifi=""
    ssid="$(iwgetid | sed 's/wlan0 \+ESSID:"\(.*\)"/\1/')"
    if [ -n "$ssid" ]; then
      wifi+=" $ssid"
    fi
  fi
  full="$wifi"
fi

if [ -d /sys/class/net/eth0 ]; then
  if [ "$(cat /sys/class/net/eth0/operstate)" = "up" ]; then
    if [ "$(cat /sys/class/net/eth0/carrier)" = "1" ]; then
      eth=""
    else
      eth=""
    fi
  fi
  full="$eth"
fi

if [ -n "$eth" -a -n "$wifi" ]; then
  full="$eth $wifi"
fi

echo "$full"
